version: "3.8"
services:
  cpe-siren:
    build: .
    ports:
      - 3009:3000
    environment:
      - MONGO_URI=mongodb://root:cp3$!r3n@mongodb:27017/CPE-Siren
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cp3$!r3n
      - MONGO_INITDB_DATABASE=CPE-Siren
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

volumes:
  mongodb_data:
